apiVersion: v1
kind: Service
metadata:
  name: service
spec:
  type: NodePort
  selector:
    app: service
  ports:
    - protocol: TCP
      port: 32000
      targetPort: 32000
      nodePort: 32000
